// <auto-generated />
using System;
using CuponTakeInfra.Db.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CuponTakeInfra.Auth.Migrations
{
    [DbContext(typeof(MainClusterDb))]
    partial class MainClusterDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CuponTakeInfra.Db.Models.CuponDbModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt")
                        .HasColumnOrder(3);

                    b.Property<string>("cuponCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CuponCode")
                        .HasColumnOrder(1);

                    b.Property<int>("ownerid")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("ownerid");

                    b.ToTable("Cupons");
                });

            modelBuilder.Entity("CuponTakeInfra.Db.Models.RedeemCuponHistory", b =>
                {
                    b.Property<string>("redeemProtocol")
                        .HasColumnType("text")
                        .HasColumnName("Protocol")
                        .HasColumnOrder(0);

                    b.Property<int>("redeemByid")
                        .HasColumnType("integer");

                    b.Property<int>("redeemCuponid")
                        .HasColumnType("integer");

                    b.HasKey("redeemProtocol");

                    b.HasIndex("redeemByid");

                    b.HasIndex("redeemCuponid");

                    b.ToTable("RedeemCuponHistory");
                });

            modelBuilder.Entity("CuponTakeInfra.Db.Models.UserDbModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("character varying(90)")
                        .HasColumnName("Password")
                        .HasColumnOrder(2);

                    b.Property<int>("points")
                        .HasColumnType("integer")
                        .HasColumnName("Points")
                        .HasColumnOrder(3);

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Username")
                        .HasColumnOrder(1);

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CuponTakeInfra.Db.Models.CuponDbModel", b =>
                {
                    b.HasOne("CuponTakeInfra.Db.Models.UserDbModel", "owner")
                        .WithMany()
                        .HasForeignKey("ownerid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("owner");
                });

            modelBuilder.Entity("CuponTakeInfra.Db.Models.RedeemCuponHistory", b =>
                {
                    b.HasOne("CuponTakeInfra.Db.Models.UserDbModel", "redeemBy")
                        .WithMany()
                        .HasForeignKey("redeemByid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CuponTakeInfra.Db.Models.CuponDbModel", "redeemCupon")
                        .WithMany()
                        .HasForeignKey("redeemCuponid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("redeemBy");

                    b.Navigation("redeemCupon");
                });
#pragma warning restore 612, 618
        }
    }
}
