// <auto-generated />
using System;
using CouponTakeInfra.Db.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CouponTakeInfra.Auth.Migrations
{
    [DbContext(typeof(MainClusterDb))]
    [Migration("20230108130651_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CouponTakeInfra.Db.Models.CouponDbModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt")
                        .HasColumnOrder(3);

                    b.Property<string>("couponCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CouponCode")
                        .HasColumnOrder(1);

                    b.Property<int>("ownerid")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("ownerid");

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("CouponTakeInfra.Db.Models.RedeemCouponHistory", b =>
                {
                    b.Property<string>("redeemProtocol")
                        .HasColumnType("text")
                        .HasColumnName("Protocol")
                        .HasColumnOrder(0);

                    b.Property<int>("redeemByid")
                        .HasColumnType("integer");

                    b.Property<int>("redeemCouponid")
                        .HasColumnType("integer");

                    b.HasKey("redeemProtocol");

                    b.HasIndex("redeemByid");

                    b.HasIndex("redeemCouponid");

                    b.ToTable("RedeemCouponHistory");
                });

            modelBuilder.Entity("CouponTakeInfra.Db.Models.UserDbModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("character varying(90)")
                        .HasColumnName("Password")
                        .HasColumnOrder(2);

                    b.Property<int>("points")
                        .HasColumnType("integer")
                        .HasColumnName("Points")
                        .HasColumnOrder(3);

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Username")
                        .HasColumnOrder(1);

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CouponTakeInfra.Db.Models.CouponDbModel", b =>
                {
                    b.HasOne("CouponTakeInfra.Db.Models.UserDbModel", "owner")
                        .WithMany()
                        .HasForeignKey("ownerid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("owner");
                });

            modelBuilder.Entity("CouponTakeInfra.Db.Models.RedeemCouponHistory", b =>
                {
                    b.HasOne("CouponTakeInfra.Db.Models.UserDbModel", "redeemBy")
                        .WithMany()
                        .HasForeignKey("redeemByid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CouponTakeInfra.Db.Models.CouponDbModel", "redeemCoupon")
                        .WithMany()
                        .HasForeignKey("redeemCouponid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("redeemBy");

                    b.Navigation("redeemCoupon");
                });
#pragma warning restore 612, 618
        }
    }
}
